name: Mondoo GitHub Organization scan
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  mondoo-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mondoohq/actions/github-org@v0.9.3
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          organization: mondoohq
          is-cicd: false
