name: Mondoo GitHub Organization scan
on:
  push:
  schedule:
    - cron: "0 * 1 * *"
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mondoohq/actions/github-org@main
        with:
          service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: mondoohq
          is-cicd: false
